-- СПРАЙТЫ
table.insert(Sprites, DetailSprite("hud-detail-boombox", "boombox3", path))
table.insert(Sprites, ButtonSprite("hud-boombox-icon", "HUD/HUD-boombox", nil, ButtonSpriteBottom, nil, nil, path))

-- ГЛАВНЫЙ БУМБОКС
table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = true,
	SaveName = "BoomBox_base",
	FileName = path .. "/devices/boombox_base.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 300,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1500,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Tech = true,
	Upgrades =
	{
		{ Enabled = true, SaveName = "BoomBox_old", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = 300 },
	},
})

-- МЕНЮ СТАРЫХ ПЕСЕН
table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "BoomBox_old",
	FileName = path .. "/devices/boombox_old.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades =
	{
		{ Enabled = true, SaveName = "BoomBox_base", MetalCost = 0, EnergyCost = -300 },
	},
})

-- МЕНЮ НОВЫХ ПЕСЕН
table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "BoomBox_new",
	FileName = path .. "/devices/boombox_new.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades =
	{
		{ Enabled = true, SaveName = "chainsaw_man_kick_back", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "flame_brigade_ending", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "flame_brigade_opening", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "stupid_pig_dream", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "renai_circulation", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "tokyo_ghoul_unravel", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "kino_tsoy_summer_ends", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "caesar_ep_zenless", MetalCost = 0, EnergyCost = 300 },
		{ Enabled = true, SaveName = "BoomBox_base", MetalCost = 0, EnergyCost = -300 },
	},
})

-- ПЕСНИ
table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "chainsaw_man_kick_back",
	FileName = path .. "/devices/chainsaw_man_kick_back.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})

table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "flame_brigade_ending",
	FileName = path .. "/devices/flame_brigade_ending.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})

table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "flame_brigade_opening",
	FileName = path .. "/devices/flame_brigade_opening.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})

table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "stupid_pig_dream",
	FileName = path .. "/devices/stupid_pig_dream.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})

table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "renai_circulation",
	FileName = path .. "/devices/renai_circulation.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})

table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "tokyo_ghoul_unravel",
	FileName = path .. "/devices/tokyo_ghoul_unravel.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})

table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "kino_tsoy_summer_ends",
	FileName = path .. "/devices/kino_tsoy_summer_ends.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})

table.insert(Devices, IndexOfDevice("sandbags") + 1,
{
	Enabled = false,
	SaveName = "caesar_ep_zenless",
	FileName = path .. "/devices/caesar_ep_zenless.lua",
	Icon = "hud-boombox-icon",
	Detail = "hud-detail-boombox",
	BuildTimeIntermediate = 1,
	BuildTimeComplete = 1,
	ScrapPeriod = 5,
	MetalCost = 1,
	CanMove = true,
	MovePeriod = 5.5,
	EnergyCost = 1,
	PopulationCap = 1,
	MetalRepairCost = 0,
	EnergyRepairCost = 0,
	MetalReclaimMin = 0.25,
	MetalReclaimMax = 0.5,
	EnergyReclaimMin = 0.1,
	EnergyReclaimMax = 0.5,
	MaxUpAngle = StandardMaxUpAngle,
	BuildOnGroundOnly = false,
	SelectEffect = "ui/hud/devices/ui_devices",
	Upgrades = { { Enabled = true, SaveName = "BoomBox_new", MetalCost = 0, EnergyCost = -300 } },
})